import Header from "../Header";
import Rubrik from "../Rubrik";
import KoehlerPortrait from '../../images/ckoehler/ckoehler-portrait.jpg';
import Footer from "../Footer";
import UpArrow from "../UpArrow";

function Koehler(props) {
    return (
        <div id="Wrapper" className="container_14">
            <div id="Header">
                <Header id={props.author} />
                <div className="grid_9">
                    <h1 id="main_title">VIVALDI und ich. Ein persönlicher Rückblick</h1>
                    <p id="author">Carola Köhler, Berlin</p>
                </div>
                <Rubrik />
            </div>

            <div id="Teasers" className="clearfix">
                <div className="grid_9">
                    {/* <!-- erster Abschnitt hier einfuegen --> */}
                    <p>Zum Sommersemester 1996 wechselte ich von Heidelberg an die Humboldt-Universität zu Berlin, nicht ahnend, dass es in meinem Leben schon bald einen treuen Begleiter geben sollte, dessen Name dem eines italienischen Barockkomponisten zum Verwechseln ähnlich sah. In Heidelberg hatte ich Germanistik, Romanistik und Kunstgeschichte studiert, in Berlin war man differenzierter, so dass ich nun für Neuere deutsche Literatur, Italianistik und ebenfalls Kunstgeschichte eingeschrieben war. Der Namenswechsel brachte das entsprechende Scheinchaos mit sich, ich hatte jetzt an einigen Stellen zu viel, an anderen dafür zu wenig. Unter anderem fehlte mir ein Hauptseminarschein in italienischer Sprachwissenschaft. Sprachwissenschaft war damals nichts, was mich zu Begeisterungsstürmen hingerissen hätte, war ich doch viel zu sehr von meiner  intrinsischen literaturwissenschaftlichen Begabung überzeugt. Auch hatten es die bislang von mir besuchten Einführungen und Proseminare nicht vermocht, in mir einen Funken zu entzünden.
                    </p>
                </div>
                <div className="grid_5">

                    <div className="abouttheauthor">
                        {/* <!-- Authorbild --> */}
                        <img src={KoehlerPortrait} width="100"
                            height="150" alt="Carola Köhler - Portrait" />
                        <div className="abouttheauthorfont"><br /><br />
                            {/* <!-- Authorbeschreibung (Text) --> */}
                            <b>Carola Köhler</b>, M.A., freie Lektorin. Studium der Neueren deutschen Literatur, Italianistik und Kunstgeschichte in Heidelberg, Bari und Berlin. 1996–2000 studentische Hilfskraft, 2001–2007 wissenschaftliche Mitarbeiterin in der italienischen Sprachwissenschaft am Lehrstuhl von Dieter Kattenbusch. Während der gesamten Zeit 1996–2007 kontinuierliche Mitarbeit im Projekt VIVALDI, seither sporadisch.
                        </div>
                        <div className="clearfloat"></div>
                    </div>
                </div>
            </div>

            <div id="Main">
                <div id="Articles" className="grid_14">
                    <section id="posts">
                        <article className="post">
                            {/* <!-- Content of the article --> */}
                            <p>
                                Am Institut für Romanistik, das damals noch im geschichtsträchtigen Gebäude Dorotheenstr. 1 residierte, welches ebenso wie viele andere Gebäude in der Umgebung die Narben der Einschusslöcher trug, die es im Kampf um Berlin davongetragen hatte, war die Auswahl an Hauptseminaren in italienischer Sprachwissenschaft recht übersichtlich. Im Vorlesungsverzeichnis  entdeckte ich ein Hauptseminar zur italienischen Dialektologie eines Professor Kattenbusch, dessen Name mir allerdings nichts sagte. Da ich aber sowieso keinen der Lehrenden am Institut für Romanistik kannte, nahm ich als Auswahlkriterien Thema und Uhrzeit. Das Seminar begann um zehn, zum Glück. Hätte Dieter Kattenbusch nämlich schon damals die Angewohnheit gehabt, auf die Randzeiten auszuweichen und um acht begonnen, wären wir uns mit Sicherheit nie begegnet. So aber radelte ich jeden Mittwochmorgen von Steglitz über die Großbaustelle Potsdamer Platz nach Mitte und schaffte es meistens sogar, halbwegs pünktlich zu sein.
                            </p>
                            <p>
                                Das Thema italienische Dialektologie wiederum schien mir eine gewisse Lebensnähe zu besitzen, von der ich mir vorstellte, dass sie mir den Zugang zur wissenschaftlichen Betrachtung erleichtern würde. Mit der Vielfalt der italienischen Dialekte hatte ich mich schließlich während eines Erasmus-Aufenthalts, den ich 1992/93 in Bari verbracht hatte, schon ein bisschen beschäftigt. Mangels vernünftig ausgestatteter Bibliotheken und didaktisch sinnvoller Konzepte in der Hochschulausbildung hatte ich damals meine Studien in den Alltag verlagert und dabei die verschiedenen  Haltungen dem Dialekt gegenüber kennengelernt, die unterschiedlich ausgeprägte Dialektkenntnisse mit sich brachten. Während die baresische Mittelstandsfamilie, bei der ich wohnte, froh war, den Dialekt ihrer Eltern hinter sich gelassen zu haben, weil das zur Komplettierung ihres sozialen Aufstiegs beitrug, ornamentierten viele der gleichaltrigen Studierenden, mit denen ich mich traf, ihre Rede mit einzelnen dialektalen Wörtern oder Floskeln. Kaum jemand von ihnen war aber in der Lage, ein Gespräch flüssig im Dialekt zu führen. In der Altstadt von Bari hingegen, die räumlich damals vom Rest der Stadt wesentlich stärker als heute separiert  war, lebten die Menschen, für die der Dialekt Muttersprache und vorrangiges Kommunikationsmittel war. Zwischen <i>Bari vecchia</i> und <i>Bari per bene</i> hing der Haussegen allerdings nicht nur in sprachlicher, sondern auch in sozialer Hinsicht schief, wobei sich hier die gegenseitige Beeinflussung gut studieren ließ. Die <i>baresi per bene</i> gingen niemals freiwillig in die <i>città vecchia</i>, weil sie befürchteten, auf offener Straße ausgeraubt zu werden. Unter anderem deshalb verwendeten sie auch den Dialekt nicht mehr, denn der war für sie eindeutig als Sprache der <i>malavita</i> konnotiert und daher mit geringem sozialem Prestige verbunden. Für die <i>baresi della città vecchia</i> hingegen war der Dialekt Teil ihrer Identität, häufig stand ihnen auch keine adäquate sprachliche Alternative zur Verfügung. Zwar leugneten sie nicht, dass einige unter ihnen beträchtliche Probleme mit der Staatsgewalt hatten, empfanden es jedoch als Unrecht, pauschal als „unehrenhaft“ abgestempelt zu werden. Von daher pflegten sie den Dialekt als Ausdruck ihrer besonderen Verbundenheit zu ihrer <i>terra barese</i> und benutzten ihn gleichzeitig geradezu trotzig, um sich gegen die <i>baresi per bene</i> abzugrenzen, was diese wiederum mit hochmütiger Verachtung und sozialer Stigmatisierung quittierten.
                            </p>
                            <p>
                                Mit diesem Erfahrungswissen ausgestattet, begann ich also, den Erwerb eines Hauptseminarscheins in italienischer Dialektologie zu verfolgen. Allerdings fehlten mir damals nicht nur ein paar Scheine, um an der Uni voranzukommen, sondern ebenfalls welche, um meinen Lebensunterhalt zu bestreiten: Ich brauchte dringend einen Job. Bei einer vorangegangenen Sondierung, die ich vorgenommen hatte, um mich zwischen der HU und der FU zu entscheiden, war mir aufgefallen, dass es an der HU öffentliche Ausschreibungen für Stellen als studentische Hilfskräfte gab. In Heidelberg hatte ich durch großen Zufall solch eine Stelle gehabt, allerdings bei einem Professor für Molekulare Biophysik am Deutschen Krebsforschungszentrum, für den ich vor allem Artikel aus Fachzeitschriften herausgesucht und kopiert hatte. An der Uni selbst hatte es eher mau ausgesehen, die wenigen Stellen, die es dort gab, waren in der Regel, wie es sich für ein feudalrechtlich organisiertes Gemeinwesen gehört, von Professors Gnaden an einige Auserwählte vergeben worden, die es mit dem entsprechenden huldvollen Verhalten dankten. Aus diesem Grund hatten es mir die öffentlichen Ausschreibungen an der HU sofort angetan, zumal daraus ersichtlich war, dass diese Stellen deutlich besser bezahlt wurden als im Süden, während gleichzeitig die Arbeitszeit tarifvertraglich geregelt war und die Stellen zudem für zwei Jahre vergeben wurden. Ich hatte mir also fest vorgenommen, mich auf eine solche Stelle zu bewerben. Am Institut für Germanistik, wo ich im Februar noch jede Menge Aushänge gesehen hatte, herrschte nun im April gähnende Leere. Fast hatte es den Anschein, als wäre die in Heidelberg übliche Praxis der Stellenvergabe in den vergangenen zwei Monaten nach Berlin diffundiert und ich hier nun vom Regen in die Traufe gekommen.
                            </p>
                            <p>
                                Dann aber kam mir der Zufall (oder war es Vorbestimmung) zuhilfe. Nicht nur ich war  neu in der Stadt und kannte  kaum jemanden, auch Dieter Kattenbusch war  gerade erst von Gießen zugezogen, um hier seine Professur anzutreten. Entsprechend kannte auch er niemanden. Er hatte jedoch zwei Stellen als studentische Hilfskraft zu besetzen,  und so scheute er sich nicht, in seinem Hauptseminar ein bisschen Werbung dafür zu machen. Von Dialektaufnahmen war da die Rede und einem sprechenden Sprachatlas; die Erwartungen einiger Mitstudenten, nun selbst als Exploratoren gen Italien zu ziehen, dämpfte er jedoch sofort. Vielmehr sollte es, neben der unvermeidlichen Kopierarbeit, um die Verarbeitung der Sprachdaten gehen. Alles in allem blieb die Aufgabenbeschreibung etwas vage. Ich bewarb mich und wurde tatsächlich zu einem Vorstellungsgespräch eingeladen. Professor Kattenbusch schlug mir gleich vor, gemeinsam in die Mensa essen zu gehen, natürlich standesgemäß in die sogenannte Professorenmensa, die damals noch existierte und sich von der normalen Mensa darin unterschied, dass man hier bedient wurde und Tischdecken auf den Tischen lagen. Auf dem Weg eröffnete er mir, dass er sich eigentlich schon für mich entschieden hätte. Während ich versuchte, neben ihm Schritt zu halten, erklärte er mir, dass ihn mein Lebenslauf beeindruckt hätte, so dass ihm die Wahl nicht schwer gefallen sei. Ich war sehr erstaunt, hatte ich die bunte Vielfalt meines Lebenslaufs bisher eigentlich eher als hinderlich für eine akademische Laufbahn angesehen, aber gleichzeitig freute ich mich, das die Welt manchmal doch anders funktioniert als erwartet.
                            </p>
                            <p>
                                Es dauerte ein bisschen, bis alle Formalitäten erledigt waren und ich meine Arbeit aufnehmen konnte. Mit mir begann der einzige männliche Bewerber, Jochen Schmidt, dessen Informatiknebenfachstudium wohl den Ausschlag zu seiner Auswahl gegeben hatte. Professor Kattenbuschs Ziel war es, unabhängig von Fernleihen zu werden, deshalb bestand eine unserer Aufgaben darin, die Fachliteratur in den noch nicht durch ein Verbundsystem miteinander vernetzten Bibliotheken Berlins sowie darüber hinaus ausfindig zu machen. Was nicht in der Institutsbibliothek vorhanden war, musste herangeschafft und kopiert werden. Da die Bibliothek des Instituts für Romanistik sich zu jener Zeit noch nicht von der realsozialistischen Mangelwirtschaft erholt hatte und wahrlich nicht üppig ausgestattet war, gab es jede Menge zu tun. Woche für Woche legten wir Professor Kattenbusch schwere Papierpacken kopierten Materials auf den Tisch, die dieser dann mit nach Hause nahm und dort zu einer Art Hilfsbuch verleimte.
                            </p>
                            <p>
                                Aber unsere eigentliche Aufgabe stand uns noch bevor: Professor Kattenbusch hatte vor, uns zu Mitstreitern seines Lebenswerks zu machen. Es trug den Namen VIVALDI, was laut seinen Erklärungen ein Akronym war, das wiederum die Weiterentwicklung des vor allem von Italienern fälschlicherweise als Aldi gelesenen Kürzels ALD-I des Schwesterprojekts in Salzburg darstellte. Professor Kattenbusch plante nämlich nichts Geringeres, als in die Fußstapfen der beiden Schweizer Sprachatlasproduzenten Karl Jaberg und Jakob Jud zu treten und einen Sprachatlas der Dialekte und Minderheitensprachen Italiens zu erstellen. Die Rolle der damaligen Exploratoren Paul Scheuermeier, Max Leopold Wagner und Gerhard Rohlfs wollte er auch gleich noch mit ausfüllen. Das Besondere an dem Atlas aber sollte nun sein, dass der sich die technische Entwicklung zunutze machen sollte, um – anders als sein Vorgänger – nicht nur die Trias von geographischer Karte, hochsprachlichem Stimulus und Transkription der dialektalen Antwort abzubilden, sondern diese zur Tetraktys zu erweitern, indem die dialektale Antwort – das eigentliche Herz bei der Sprachatlaserstellung – zusätzlich auch als Tondatei zur Verfügung gestellt würde. Statt großformatigen, umständlich zu handhabenden Sprachatlasbänden sollte – so die Vorstellung– das gesamte Material elegant auf einer CD gebündelt werden. Entstanden war die Idee eines sogenannten sprechenden Sprachatlasses während der Aufnahmen für den ALD, den ladinischen Sprachatlas unter der Leitung von Professor Goebl in Salzburg, zu dessen <i>équipe d’explorateurs</i> Dieter Kattenbusch gehört hatte. Als Quelle der Inspiration hatte der Legende zufolge die Jugendzeitschrift <i>Bravo</i> gedient, die ihren Heften in den Siebzigern häufig aus einfachem Material hergestellte Schallplatten mitgegeben hatte, auf denen sich die neuesten Hits befanden und die sich, nachdem man sie einige Male abgespielt hatte, schnell bis zur Unbrauchbarkeit abnutzten. Was zeigt, dass nicht alles schlecht ist, was als kommerzielles Produkt daherkommt. Da der technische Fortschritt inzwischen die CD als Medium der Wahl erschienen ließ, hatte sich Dieter Kattenbusch zusammen mit seinem Freund und Kollegen Roland Bauer überlegt, dass es nun an der Zeit wäre, so etwas auch für Italien zu realisieren. Daraufhin hatten sie flugs ein Fragebuch entwickelt und waren nach Sizilien aufgebrochen, um dort die ersten Sprachaufnahmen zu machen.
                            </p>
                            <p>
                                Zwei wissenschaftliche Artikel, in denen das Projekt vorgestellt wurde, sowie zwei Handvoll Kassetten mit Sprachaufnahmen aus Sizilien, das war der Stand der Dinge, als Dieter Kattenbusch nach Berlin kam und nun die Chance sah, dieses Projekt auf institutionelle Füße zu stellen und voranzutreiben. Wenn es ihm gelänge, jedes Jahr eine Region zu explorieren, so seine Rechnung, müsste er bis zu seiner Pensionierung fertig sein. Aber erst mal ging es darum, sich das entsprechende informatische Know-how zu verschaffen. Dazu schickte Professor Kattenbusch seine beiden frisch gebackenen studentischen Hilfskräfte auf Dienstreise nach Salzburg. Wir sollten uns dort, in der Werkstatt des ALD, mit den Programmen versorgen lassen, die man zur Bearbeitung der Daten und zu ihrer Präsentation auf einer CD benötigte. Im Spätherbst machten wir uns per Nachtzug und mit meinem Laptop mit Schwarzweißdisplay auf den Weg und wurden in Salzburg als erstes gefragt, wo denn die Transkriptionen seien, die man in die Datenbank einzupflegen gedächte. Transkriptionen? Nun, von Transkriptionen wussten wir nichts, und nur langsam begriffen wir, welche Arbeitsschritte wie zu durchlaufen waren, damit am Ende eine akustische Reise durch Italien möglich sein würde. Dass die Transkriptionen nach wie vor ganz traditionell anzufertigen waren, trug zu einer gewissen Desillusionierung über die Möglichkeiten des Computereinsatzes bei. Das ALD-Team klopfte uns aufmunternd auf die Schultern, lud uns nach einer geduldigen Einführung das Laptop mit allen Programmen und Datenbanken voll, die es nutzte und teilweise selbst entwickelt hatte, und wünschte uns gutes Gelingen.
                            </p>
                            <p>
                                Wieder zurück in Berlin, berichteten wir getreulich, was wir erfahren hatten, und versuchten nachzuvollziehen, wie alles funktionierte, während Professor Kattenbusch erst mal mit dem Anfertigen der Transkriptionen beschäftigt war. Für meinen Hauptseminarschein hatte ich mich mit einem der sizilianischen Dialekte näher beschäftigt und dafür auch die Transkription einer Sprachaufnahme angefertigt. Besonders die Unterscheidung der verschiedenen Öffnungsgrade bei den Vokalen hatte sich mir nicht zur Gänze erschlossen, so dass ich froh war, dass er diese Arbeit nun erst mal allein verrichtete. In der Zwischenzeit versuchte ich vor allem die Datenbank zu verstehen, in die die Transkriptionen dann eingegeben werden mussten. Ich zeigte das alles meinem damaligen Freund, Marcel Lucas Müller, der seit Jahren programmierte, gerade sein Medizinstudium beendet hatte und sich unschlüssig war, ob er eher Augenarzt werden oder in Richtung Medizinische Informatik gehen sollte. Er sah sich alles genau an und fragte mich, was wir denn mit dieser zwar ausgezeichneten, aber für unsere Verhältnisse überdimensionierten Datenbank anfangen wollten. Eigentlich waren es ja nicht besonders viele Informationen, die wir zu verarbeiten hatten. Dazu kam als Nachteil die fehlende Kontrollmöglichkeit der Transkriptionen  während der Eingabe, da die Datenbank entwickelt worden war, bevor sich die graphische Benutzeroberfläche flächendeckend durchgesetzt hatte. Wegen der vielen benötigten Sonderzeichen wurden die Transkriptionen in einer Art Code eingegeben, der sich aus verschiedenen Schriftarten zusammensetzte. Dieser konnte nicht direkt à la <i>What you see is what you get</i>, sondern erst beim Ausdruck visualisiert werden.
                            </p>
                            <p>
                                An dieser Stelle erwachte der informatische Ehrgeiz in Marcel, eine maßgeschneiderte Lösung zu entwickeln, die bedienfreundlich und genau auf unsere Verhältnisse zugeschnitten war. Nach ein paar Programmiernachtschichten präsentierte er mir das Ergebnis, das er VivTKA nannte, Vivaldi-Transkriptionsassistentin, denn das sollte sie für mich, die ich mutmaßlich die Transkriptionen einzugeben hatte, sein. Es war eine Tabelle, in der jedes Tabellenblatt einer Region zugeordnet war.  In der ersten Spalte standen die Stimuli, in der ersten Zeile die Orte. Auf diese Weise war es möglich, jede Transkription eindeutig zu identifizieren. Diese wurden nach dem in Salzburg entwickelten Code aus verschiedenen Schriftarten eingegeben, der über ein Makro sofort in die endgültige Transkription umgewandelt wurde, so dass man gleich sehen konnte, ob man sich verschrieben hatte oder nicht. Außerdem war es möglich, über einen Shortcut das Audioverarbeitungsprogramm aufzurufen, so dass man erstens die geschnittene Tondatei sofort kontrollieren, sie zweitens nachbearbeiten und drittens mit der Transkription vergleichen konnte. Somit waren alle notwendigen Informationen zentral zugänglich, zudem konnten jederzeit neue Orte (=Spalten) oder neue Regionen (=Tabellenblätter) hinzugefügt werden. Angereichert war die VivTKA mit verschiedenen Exportfunktionen, wobei Marcel darauf geachtet hatte, dass der Export in die Salzburger Datenbank jederzeit möglich war.
                            </p>
                            <p>
                                Ich zeigte alles Professor Kattenbusch, den das sehr begeisterte und der sehr erfreut war, auf diese Weise einen weiteren Mitarbeiter für sein Projekt gewonnen zu haben. Jetzt konnte die Arbeit also wirklich losgehen: Tondateien in kleine Schnipsel schneiden, Transkriptionen eintragen und einen Kontrolldurchgang zur Korrektur machen. Damit waren wir erst mal eine ganze Weile beschäftigt.
                                Das Einspielen der Bänder war mühsam, die Leistungsfähigkeit der Computer zur damaligen Zeit begrenzt, nicht das gesamte Band, sondern nur Stückchen für Stückchen konnte eingespielt werden. Auch das Transkribieren, das Eintragen der Transkriptionen und die Kontrolle dauerten. Es ging einige Zeit ins Land, und zwischendurch rückte das Ziel, alle zwanzig Regionen Italiens innerhalb eines überschaubaren Zeitraums zu explorieren, manchmal in weite Ferne. Voller Hochachtung dachten wir immer wieder an die Vorväter, die unter wesentlich schlechteren Bedingungen Großes geleistet hatten. Aber wir machten weiter. Professor Kattenbusch hatte unsere HiWi-Verträge inzwischen verlängern lassen, so dass wir ihm weitere zwei Jahre bei seinen Bemühungen, der Menschheit einen Dienst zu erweisen, behilflich sein konnten.
                            </p>
                            <p>
                                Irgendwann hatten wir genug Material zusammen, um in die nächste Phase einzusteigen: die Datenpräsentation. Während wir überlegten, wie wir mit den vorhandenen Mitteln eine CD erstellen sollten, fragte mich Marcel, der sich inzwischen zum Sprachatlasexperten gemausert hatte, ob wir nicht mal daran gedacht hätten, den Sprachatlas im Internet anzusiedeln. Das sei schließlich das Medium der Zukunft und hätte den großen Vorteil, dass es ständig erweiter- und aktualisierbar sei und man von überall auf der Welt darauf zugreifen könne. Er hätte da schon mal was vorbereitet. Ich berichtete alles Professor Kattenbusch und der meinte, natürlich wolle er sich das mal ansehen. Was er dann sah, begeisterte ihn. Marcel hatte es dank eines Java-Applets tatsächlich geschafft, eine Internetanwendung zu entwickeln, bei der zur gleichen Zeit eine Karte, der italienische Stimulus und die Transkription zu sehen und die dialektale Antwort zu hören waren. Das war in jedem Fall ein Novum, denn bei vielen anderen Versuchen, die wir im Internet gesehen hatten, gab es meist einen Haken. Entweder mussten separate Programme installiert werden oder man konnte die Informationen nur nacheinander abrufen. Meist klappte irgendetwas nicht richtig und es war mühsam, sich durch die Seiten zu navigieren. Das einzige Manko am Applet hingegen war die nicht besonders gute Tonqualität, da es nur ein sehr spezielles Format verarbeiten konnte, aber das sollte sich im Lauf der Zeit ändern, die technische Entwicklung arbeitete für uns. Auch der von Professor Kattenbusch bescheiden vorgetragenen Bitte nach einer CD, damit man wenigstens irgendetwas Materielles in Händen hätte statt nur einer Internetadresse, kam Marcel nach, da die gesamte Anwendung so konzipiert war, dass sie auch auf CD gebracht werden konnte.
                            </p>
                            <p>
                                Wir hatten das Gefühl, einen Meilenstein in der Sprachgeographie gesetzt zu haben. Ein Problem war allerdings inzwischen das geringe Datenmaterial. Seit den Sizilien-Aufnahmen hatte es keine weiteren gegeben, so dass es schwer war, sich vorzustellen, welches Datenreservoir dieser Sprachatlas sein könnte und wie sich damit dann auch arbeiten ließe. Denn das war ja eine Intention des gesamten Unternehmens: belastbares Datenmaterial für wissenschaftliche und didaktische Zwecke bereitzustellen. Also ging Professor Kattenbusch im September 1999 wieder <i>on tour</i>, dieses Mal graste er Sardinien ab. Währenddessen fuhr ich mit Marcel zum Romanistentag nach Osnabrück, um VIVALDI der wissenschaftlichen Öffentlichkeit vorzuführen und als Modell für ähnlich gelagerte Projekte vorzustellen. Die Reaktionen waren eher verhalten, zumindest korrespondierten sie nicht mit unserer Begeisterung ob der technischen Revolution, die wir da präsentierten. Vielleicht sind eine studentische Hilfskraft und ein Mediziner in diesem Rahmen auch nicht die geeigneten Personen, um einen wissenschaftlichen Aha-Effekt auszulösen. Aber wir ließen uns davon nicht entmutigen, sondern verstanden das eher als Ansporn, weiterzumachen und die Tragfähigkeit unserer technischen Lösungen unter Beweis zu stellen.
                            </p>
                            <p>
                                So ging es dann ein paar Jahre. VIVALDI war ein wichtiger Teil meines Lebens geworden. Ich beendete mein Studium, aus Professor Kattenbusch wurde Dieter, bei dem ich eine Stelle als wissenschaftliche Mitarbeiterin bekam. Ich machte meine erste Sprachaufnahmereise nach Ligurien, der weitere folgen sollten. Ich war weiterhin die Schnittstelle zwischen dem Romanisten und dem Informatiker. Marcel hatte Ideen, die er mit mir besprach und deren Umsetzung ich dann Dieter zeigte, der ein ums andere Mal begeistert war. Und wenn dieser einen Wunsch hatte, teilte er mir den mit und ich gab ihn an Marcel weiter, der dann schaute, was sich machen ließ. Die Tonqualität wurde besser, die Seiten wurden mithilfe einer Datenbank dynamisch, so dass die Transkriptionen nun bei einer Anfrage in Echtzeit erzeugt werden, immer wieder kam auch eine neue Region hinzu. Die VivTKA verrichtete treu ihre Dienste, ab und zu bekam sie eine neue Exportfunktion. Irgendwann trennten sich Marcels und meine Wege. Die Einzelauswahl von Stimulus und Ort, die wir noch zusammen konzipiert hatten, setzte er zuerst beim ALD in Salzburg um, bevor sie auch bei VIVALDI implementiert wurde. Den nächsten Meilenstein jedoch, die Zusammenführung der VIVALDI-Daten mit <i>Google Maps</i> zu <i>VIVALDI Maps</i>, setzte er wieder in Berlin. Damit ist es möglich, alle dialektalen Antworten auf einen Blick zu erfassen und bequem von einer Region in eine andere zu gelangen. Schaltet man von der Karte auf die Satellitenaufnahme um, lassen sich die topographischen Spezifika erkennen. Mit der Zoomfunktion gelangt man mit wenigen Mausklicks von ganz Italien über die Regionen bis hin zu den einzelnen Orten. Jetzt lässt sich tatsächlich eine virtuelle Reise durch die Dialektlandschaften Italiens unternehmen! Irgendwann war meine Zeit am Institut dann abgelaufen, mein Vertrag endete, so dass Marcel und ich den Stab an Fabio Tosques weitergaben, der sowohl im Feld unterwegs ist als auch die informatische Betreuung übernommen hat.
                            </p>
                            <p>
                                Und heute? Nun, ich wohne schon lange nicht mehr in Steglitz und meine Beziehung zu VIVALDI ist lockerer geworden, wir haben uns voneinander abgenabelt. Ich verfolge weiterhin mit Interesse den Fortgang des Projekts, bin aber nicht mehr über jeden seiner Schritte informiert. Ich freue mich darüber, dass es voran geht und die Italienkarte auf der Einstiegsseite sich immer mehr füllt. Ab und an trage ich gern noch mein Scherflein dazu bei, vielleicht ergibt sich auch mal wieder eine engere Zusammenarbeit. Das ist nicht zuletzt auch eine Frage des Geldes. Als Freiberuflerin sind längere Italienreisen problematischer als damals als wissenschaftliche Mitarbeiterin, als pünktlich jeden Monat das Gehalt auf dem Konto eintraf. Jochen Schmidt ist inzwischen Schriftsteller und betreibt seit vielen Jahren mit einigen anderen die Berliner Lesebühne <i>Chaussee der Enthusiasten</i>. Marcel Lucas Müller hat nach seiner Habilitation in Medizinischer Informatik nun doch auch noch einen Facharzt gemacht, allerdings nicht in Augenheilkunde, sondern in Dermatologie. Unsere Anwendungen laufen noch immer, das Durchhalten hat sich ausgezahlt. Die VivTKA ist weiterhin in Gebrauch und hat trotz der gestiegenen Datenmenge ihre Grenzen noch nicht erreicht. Während im Internet jederzeit der aktuelle Stand des Projekts dokumentiert ist, lassen sich über die CDs bzw. inzwischen DVDs bestimmte Zwischenzustände fixieren. Die Zahl der explorierten Regionen ist kräftig angestiegen, so dass sich virtuell immer länger durch die Dialekte und Minderheitensprachen Italiens reisen lässt, wobei die Unterschiede zwischen den norditalienischen auf der einen und den mittel- und süditalienischen Dialekten auf der anderen Seite sehr „ohrenfällig“ werden. Von der Idee über die ersten mageren Anfänge bis zu dem Punkt, an dem das Ganze eine Form gewonnen hat, war es ein langer Weg. Wer heute die <a href="https://www2.hu-berlin.de/vivaldi" target="blank">Vivaldi-Homepage</a> aufruft, dem fallen nicht zuerst die Lücken auf, die noch gefüllt werden müssen, sondern der kann auf eine tragfähige Datensammlung zugreifen, die ihresgleichen sucht.
                            </p>
                            <p className="quote">
                                <span style={{ color: "#666666" }}><b>
                                    Lieber Dieter, danke für den langen Atem und viel Energie für die weitere Wegstrecke!</b></span>
                            </p>
                        </article>
                    </section>
                </div>
            </div>
            <UpArrow />
            <Footer />
        </div>
    );
}

export default Koehler;